### ISSUE TITLE
Python import on main branch has error

### ISSUE THREAD

**Issue by stevegrubb** [openvinotoolkit/model_server#3165]
When doing a smoke test of the python environment, I get a traceback. This is in a freshly built image at commit b73e9dba that is updated to have the updated demos/python_demos/requirements.txt

**To Reproduce**
 In the image, I pip install those requirements. Then I start up the python3 interpreter and issue an import:
```
$ python3
>>> from optimum.intel.openvino import OVModelForCausalLM

/ovms/lib/python/openvino/runtime/__init__.py:10: DeprecationWarning: The `openvino.runtime` module is deprecated and will be removed in the 2026.0 release. Please replace `openvino.runtime` with `openvino`.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/optimum/intel/openvino/__init__.py", line 44, in <module>
    from .modeling import (
  File "/usr/local/lib/python3.9/site-packages/optimum/intel/openvino/modeling.py", line 54, in <module>
    from ...exporters.openvino import main_export
  File "/usr/local/lib/python3.9/site-packages/optimum/exporters/openvino/__init__.py", line 1, in <module>
    from .__main__ import main_export
  File "/usr/local/lib/python3.9/site-packages/optimum/exporters/openvino/__main__.py", line 31, in <module>
    from .convert import export_from_model, export_tokenizer
  File "/usr/local/lib/python3.9/site-packages/optimum/exporters/openvino/convert.py", line 32, in <module>
    from optimum.exporters.onnx.convert import check_dummy_inputs_are_allowed
  File "/usr/local/lib/python3.9/site-packages/optimum/exporters/onnx/convert.py", line 49, in <module>
    from .utils import (
  File "/usr/local/lib/python3.9/site-packages/optimum/exporters/onnx/utils.py", line 46, in <module>
    from diffusers.models.attention_processor import (
  File "/usr/local/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/usr/local/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/usr/local/lib/python3.9/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.9/site-packages/huggingface_hub/__init__.py)
>>> 
```
**Expected behavior**
This works fine on the 2025.0 release:
```
$ python3
>>> from optimum.intel.openvino import OVModelForCausalLM

/usr/lib64/python3.9/importlib/util.py:245: DeprecationWarning: The `openvino.runtime` module is deprecated and will be removed in the 2026.0 release. Please replace `openvino.runtime` with `openvino`.
  self.__spec__.loader.exec_module(self)
/usr/local/lib/python3.9/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/usr/local/lib/python3.9/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
>>> 
```
In case this matters the image that fails has these python packages:
huggingface-hub==0.26.0
onnx==1.17.0
openvino==2025.1
optimum==1.17.1
optimum-intel @ git+https://github.com/dtrawins/optimum-intel.git@30437ae38d2d527b46b980c3f09be884646704f9
torch==2.6.0+cpu
transformers==4.49.0

The one that works has:
huggingface-hub==0.24.7
onnx==1.17.0
openvino==2025.0
optimum==1.17.1
optimum-intel @ git+https://github.com/dtrawins/optimum-intel.git@30437ae38d2d527b46b980c3f09be884646704f9
torch==2.6.0+cpu
transformers==4.40.0

Let me know if you need anything else.

**Comment by stevegrubb** [comment]
Might be related, previously the transformers package was updated to 4.49. But on installation of the requirements.txt dependencies this conflict was identified by pip:

The user requested huggingface_hub==0.24.7
optimum[diffusers] 1.17.1 depends on huggingface-hub>=0.8.0
transformers 4.49.0 depends on huggingface-hub<1.0 and >=0.26.0

It seems like this is the set of packages involved in the above problem.

**Comment by stevegrubb** [comment]
diffusers==0.29.2 seems to solve this. I don't know what all this affects by upgrading this component this far. (It was on 0.26.3.)

**Comment by rasapala** [comment]
Thanks for info, please check if this works: https://github.com/openvinotoolkit/model_server/pull/3166

**Comment by stevegrubb** [comment]
OK, tested image creation and this fixes, it. Thanks!
